#
# Copright (c) 2015 Michele Segata <segata@ccs-labs.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#

library(shiny)
library(XML)

add.idx <- function(txt, index) {
	return (paste(txt, index, sep=''))
}

create.gear.gui <- function(gear.index, default) {
	return(
	column(width=6,
	sliderInput(
			inputId = add.idx('ratio', gear.index),
			label=paste('Gear ratio', gear.index),
			min=0.01, max=5, value=default, step=0.01
		)
	)
	)
}

get.models <- function() {
	xmld <- xmlParse('./vehicles.xml')
	xd <- xmlToList(xmld)

	models <- c()
	for (i in 1:length(xd))
		models <- c(models, xd[[i]]$.attrs[['id']])
	return (models)
}
get.car <- function(car) {
	xmld <- xmlParse('./vehicles.xml')
	xd <- xmlToList(xmld)

	for (i in 1:length(xd))
		if (xd[[i]]$.attrs[['id']] == car)
			return(i)
}
get.gear <- function(gears, gear) {
	if (gear >= length(gears))
		return (1)
	for (i in 1:length(gears))
		if (gears[[i]][['n']] == gear)
			return(gears[[i]][['ratio']])
}
get.coeffs <- function(pw) {
	coeffs <- c()
	for (i in 1:length(pw))
		coeffs <- c(coeffs, as.numeric(pw[[paste('x', i-1, sep='')]]))
	return (coeffs)
}

models <- get.models()

car <- models[1]

def.gears <- c(4.5, 2.6, 1.5, 1, 0.8, 0.7, 0.6, 0.5, 0.4)
xmld <- xmlParse('./vehicles.xml')
xd <- xmlToList(xmld)
v.index <- get.car(car)
v <- xd[[v.index]]
coeffs <- get.coeffs(v$engine$power)

def.xmin <- 0
def.xmax <- 250
def.ymin <- 0
def.ymax <- 10

#number of gears
def.n.gears         <- length(v$gears) - 1
#gears ratio
for (i in 1:(def.n.gears))
	def.gears[i]    <- get.gear(v$gears, i)
def.differential    <- v$gears$differential[['ratio']]
def.minRpm          <- v$engine$.attrs[['minRpm']]
def.maxRpm          <- v$engine$.attrs[['maxRpm']]
def.eta             <- v$engine$.attrs[['efficiency']]
def.mass            <- v$mass[['mass']]
def.massCoefficient <- v$mass[['massFactor']]
def.cAir            <- v$drag[['cAir']]
def.section         <- v$drag[['section']]
def.wheeld          <- v$wheels[['diameter']]
def.wheelf          <- v$wheels[['friction']]
#print the webpage design generated by the server


fluidPage(
	fluidRow(
		#left panel
		column(4, div(class="shiny-input-panel",
			fluidRow(
				column(width=12, selectInput(inputId = "car", "Car model:", choices=get.models(), selected=car))
			),
			fluidRow(
				column(width=3, sliderInput(inputId = "xmin", label="xmin", min=0, max=250, value=def.xmin, step=10)),
				column(width=3, sliderInput(inputId = "xmax", label="xmax", min=0, max=450, value=def.xmax, step=10)),
				column(width=3, sliderInput(inputId = "ymin", label="ymin", min=-10, max=30, value=def.ymin, step=1)),
				column(width=3, sliderInput(inputId = "ymax", label="ymax", min=-10, max=30, value=def.ymax, step=1))
			),
			fluidRow(
				column(width=6, sliderInput(inputId = "ngears", label="Number of gears", min = 1, max=7, value=def.n.gears, step = 1)),
				column(width=6, sliderInput(inputId = "differential", label="Final drive", min = 0.1, max=20, value=def.differential, step = 0.01))
			),
			fluidRow(
				conditionalPanel(condition="input.ngears >= 1",
					create.gear.gui(1, def.gears[1])
				),
				conditionalPanel(condition="input.ngears >= 2",
					create.gear.gui(2, def.gears[2])
				)
			),
			fluidRow(
				conditionalPanel(condition="input.ngears >= 3",
					create.gear.gui(3, def.gears[3])
				),
				conditionalPanel(condition="input.ngears >= 4",
					create.gear.gui(4, def.gears[4])
				)
			),
			fluidRow(
				conditionalPanel(condition="input.ngears >= 5",
					create.gear.gui(5, def.gears[5])
				),
				conditionalPanel(condition="input.ngears >= 6",
					create.gear.gui(6, def.gears[6])
				)
			),
			fluidRow(
				conditionalPanel(condition="input.ngears >= 7",
					create.gear.gui(7, def.gears[7])
				)
			)
		)),
		#main panel
		column(8,
			#plot
			fluidRow(
				column(width=12, mainPanel(plotOutput(outputId = "main_plot", height = "450px", width="900px")))
			),
			#other model parameters
			fluidRow(
				column(width=6, div(class="shiny-input-panel",
					fluidRow(
						column(width=12, sliderInput(inputId = "eta", label="Engine efficiency", min = 0, max=1, value=def.eta, step = 0.05))
					),
					fluidRow(
						column(width=6, sliderInput(inputId = "minRpm", label="Minimum RPM", min = 0, max=3000, value=def.minRpm, step = 250)),
						column(width=6, sliderInput(inputId = "maxRpm", label="Maximum RPM", min = 3000, max=10000, value=def.maxRpm, step = 250))
					),
					fluidRow(
						column(width=6, sliderInput(inputId = "wheeld", label="Wheel diameter", min = 0.1, max=1.0, value=def.wheeld, step = 0.01)),
						column(width=6, sliderInput(inputId = "wheelf", label="Wheel friction", min = 0.1, max=2, value=def.wheelf, step = 0.1))
					)
				)),
				column(width=6, div(class="shiny-input-panel",
					fluidRow(
						column(width=6, sliderInput(inputId = "mass", label="Mass", min = 100, max=5000, value=def.mass, step = 100)),
						column(width=6, sliderInput(inputId = "massCoefficient", label="Mass coefficient", min = 1, max=2, value=def.massCoefficient, step = 0.01))
					),
					fluidRow(
						column(width=6, sliderInput(inputId = "cAir", label="cAir", min = 0.1, max=2, value=def.cAir, step = 0.01)),
						column(width=6, sliderInput(inputId = "section", label="section", min = 0.1, max=10, value=def.section, step = 0.1))
					)
				))
			)
		)
	)
)
